# This is a basic workflow to help you get started with Actions

name: Aplazo test

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Cypress.io
        uses: cypress-io/github-action@v6.5.0



  
